### ISSUE TITLE
Can't use MD elements after using terms inside MD elements such as lists

### ISSUE THREAD

**Issue by very-doge-wow** [LunaticMuch/docusaurus-terminology#11]
First of all, thanks for the plugin, works really well.

The problem I have is this: When using a term inside MD elements such as lists or tables, after parsing (i.e. when the syntax has been replaced with the react component) all text in the same line behind the react component is no longer interpreted as markdown and variables in codeblocks are tried to be interpreted instead of rendered as codeblock.

Here's an example:

```md
* first entry in list
* %%second|second%% entry with code `${VARIABLE}`
```

After parsing and then building the documentation, the codeblock is not rendered but gives an error during build.
How can this be fixed?

**Comment by very-doge-wow** [comment]
Currently I don't have a sample repo as the doc I'm creating is inner source of my corporation. But you can provoke it in any docusaurus project with the plugin by simply adding a line like this to an MD doc:

```md
%%CI/CD|cicd%% test test test [test](https://github.com/)
test test
```

**Comment by very-doge-wow** [comment]
![image](https://github.com/LunaticMuch/docusaurus-terminology/assets/95224950/beac8f1c-2a8f-4eb2-a4fb-8e202c78f48c)

Here's a screenshot of the issue I mentioned. As you can see the backticks aren't interpreted but rather just rendered as plaintext.

**Comment by LunaticMuch** [comment]
Need to look at it - sorry lack of time right now

**Comment by very-doge-wow** [comment]
@LunaticMuch Any progress?

**Comment by very-doge-wow** [comment]
@LunaticMuch Any updates?

**Comment by very-doge-wow** [comment]
@LunaticMuch Are you still maintaining this repository? I'm not giving up :smile:

**Comment by LunaticMuch** [comment]
@very-doge-wow I get you are not giving up, but you are also not getting how it works. Spamming messages does not help. You got asked for a reproducible test case, which you did not provide.
You _possible_ test actually does not trigger the error. I can render perfectly the line you provided.

<img width="270" alt="Screenshot 2024-02-18 at 17 27 14" src="https://github.com/LunaticMuch/docusaurus-terminology/assets/1659414/ee43964b-dcde-4d5f-bf13-645436cfdf39">

**Comment by very-doge-wow** [comment]
No need to get passive aggressive, I do get how it works. However you said you simply needed time to work on the issue, but I never received any updates. All I did was ask if you already had made any progress, no more or less. Wasn't even meant as critisism but rather just wanted to know the status.
